// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 学习笔记、面试复盘等 — 不含简历
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '2. 面试复盘',
      link: {
        type: 'generated-index',
        description: '面试准备与复盘记录',
      },
      items: [{type: 'autogenerated', dirName: '面试复盘'}],
    },
    {
      type: 'category',
      label: '3. 学习笔记',
      link: {
        type: 'generated-index',
        description: '嵌入式学习路线、项目实践与 RTOS 笔记',
      },
      items: [{type: 'autogenerated', dirName: '学习笔记'}],
    },
    {
      type: 'category',
      label: '4. 网站运维',
      collapsed: true,
      link: {
        type: 'generated-index',
        description: '本站搭建与部署说明',
      },
      items: [{type: 'autogenerated', dirName: '网站运维'}],
    },
  ],

  resumeSidebar: [
    {
      type: 'category',
      label: '简历',
      link: {
        type: 'generated-index',
        description: '按求职方向定制的个人简历，点击卡片查看对应版本',
      },
      items: [{type: 'autogenerated', dirName: '简历'}],
    },
  ],
};

export default sidebars;
